### ISSUE TITLE
Port unit tests to Jest

### ISSUE THREAD

**Issue by dutchmartin** [Yoast/plugin-grunt-tasks#5]
Apparently nobody at Yoast uses node unit, so it is good to be consistent and use mocha for unit tests like the rest.
## Todo for this issue:
- [ ] Remove nodeunit from dependency list.
- [ ] Create new files for the Jest tests.
- [ ] Install Jest.
- [ ] Port the current tests to Jest.
- [ ] Delete the node unit tests.
